version: '3.7'

services:
  redis:
    image: redis:latest
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 6377:6379

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - redis
