from aiogram.types import InputMediaPhoto


final_photo = (
    "AgACAgIAAxkBAAMEZ6dUVZAwCzDlGD4nZ6M7PLotPr8AAvbxMRsdYEBJkRbpzV4d2UQBAAMCAAN5AAM2BA"
)

start_photo = "AgACAgIAAxkBAAMCZ6dURJJhAudx9z2pQ-tNe75VDmYAAuvxMRsdYEBJG8fzFotXw_sBAAMCAAN5AAM2BA"


box_info_photo_1 = (
    "AgACAgIAAxkBAAMNZ1DLwnt3TG6qZDwGVcCq_UtQ3MUAAg7kMRtDT4hKkcGbNX94T7sBAAMCAAN5AAM2BA"
)
box_info_photo_2 = (
    "AgACAgIAAxkBAAMPZ1DLyZPob-SxAkvfRGoFOMnLGHgAAg_kMRtDT4hK1kVVlNO96wIBAAMCAAN5AAM2BA"
)
box_info_photo_3 = (
    "AgACAgIAAxkBAAMRZ1DLzdxX5M5yxzwrN8yoNN3uDTIAAhDkMRtDT4hKnC4rvjuLbd8BAAMCAAN5AAM2BA"
)
